### ISSUE TITLE
Model not showing up...

### ISSUE THREAD

**Issue by Hargreav** [honestabelink/stonevox3d#1]
Hello!
I ran ito an issue after running your StoneVoxel 3D. It initalizes fine but it doesnt show the grid,or the  voxels. If i mouse  over where the model should be,a white plane just shows up.
I installed jre and java is updated to date.

-Running windows 7 ultimate sp 1

Thank you and have a good day.

**Comment by honestabelink** [comment]
Hi Hargreav,

Sorry you are experiencing problems.

Upon start up do you see the normal ui and it's components. If these show up, then my guess it would your graphics card. Is the card older by chance, if I may could I ask what type of card it is?

"If i mouse over where the model should be,a white plane just shows up."

Do you mean the entire window goes white or just the "floor"?

**Comment by Hargreav** [comment]
Hello
thanks for you response. Only the floor goes white, teh ui work well
As for my graphic card i have an Asus radeon 7850 HD Direct CU II

thank you

**Comment by honestabelink** [comment]
It appears like your card doesn't support one of the most recent versions of OpenGL, 4.3.

http://www.newegg.com/Product/Product.aspx?Item=N82E16814121623

Newegg shows the spec supporting up to 4.2

I _foolishly_ have set up the project to be looking to 4.3, this is why you are getting the error.

If you'd like, you can make an adjustment to fix the issue yourself right now.

Open both
`StoneVox 3D 0.0.5\shaders\FragmentShader.txt`
`StoneVox 3D 0.0.5\shaders\VertexShader.txt`

Change the line

```
#version 430

to

#version 420
```

in both files, save, and re-run StoneVox. This should resolve the issue.

Thank you for bringing this to my attention

**Comment by Hargreav** [comment]
Thank you very much it works now:)
No problem i amm glad to be of help

Thank you again
